/**
 * Postgres schema names generated by TenantsService (e.g. "tenant_taller_a_1b2c3d4e")
 * always match this shape. Enforced again here, right before any raw SQL /
 * subprocess use, since a schema name ends up interpolated into
 * `CREATE SCHEMA "<name>"` and a migration URL — never trust it came from a
 * safe source just because it's typed as `string`.
 */
const SAFE_SCHEMA_NAME = /^[a-z][a-z0-9_]{2,62}$/;

export function assertSafeSchemaName(schemaName: string): void {
  if (!SAFE_SCHEMA_NAME.test(schemaName)) {
    throw new Error(
      `Refusing to use unsafe Postgres schema name: "${schemaName}"`,
    );
  }
}

/** Appends/overrides `?schema=` on a Postgres connection URL. */
export function withSchemaParam(
  connectionUrl: string,
  schemaName: string,
): string {
  assertSafeSchemaName(schemaName);
  const url = new URL(connectionUrl);
  url.searchParams.set('schema', schemaName);
  return url.toString();
}
